version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - wildrider-network
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=wildrider

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - wildrider-network
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wildrider
    ports:
      - "5432:5432"
    networks:
      - wildrider-network
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  wildrider-network:
    driver: bridge
